spring:
  datasource:
    # inmemory db
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:gtdfan
#    username: sa
#    password:

    # postgresql db
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5433/gtdfan
      username: user
      password: password

  sql:
    init:
      # https://stackoverflow.com/a/38047021/20265936
      mode: always
      schema-locations: classpath:db/schema.sql
#      data-locations: classpath:db/data.sql

  # Jackson Serialization Issue Resolver
  jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none

  # Spring Boot color console logging
  output.ansi.enabled: always

# Logger configuration
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: WARN # set to DEBUG if too many warnings
    ru.jsft.gtdfan: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
    org.springframework: ERROR
    net.ttddyy.dsproxy.listener: DEBUG # https://vladmihalcea.com/log-sql-spring-boot/
  # https://www.codejava.net/frameworks/spring-boot/logback-rolling-files-example
  file:
    name: ${GTDFAN_ROOT}/log/gtdfan.log
  # https://stackoverflow.com/questions/29918323/how-to-configure-rolling-file-appender-within-spring-boots-application-yml
  # https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging.custom-log-configuration
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      max-history: 30

# Server configuration
server:
  port: 8090 #set your port
  servlet:
    encoding:
      charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
      enabled: true # Enable http encoding support
      force: true

#  profiles:
#    active: development

#  # Security configuration
#  security:
#    user:
#      name: user
#      password: user
