spring:
#  profiles:
#    active: development
#  # Security configuration
#  security:
#    user:
#      name: user
#      password: user

  # Database
  datasource:
    # inmemory db
    url: jdbc:h2:mem:gtdfan
    username: sa
    password:

    # postgresql db
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5433/gtdfan
#    username: user
#    password: password

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

## Logger configuration
#logging:
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#  level:
#    org.springframework: info
#    org.hibernate: debug

# Server configuration
server:
  port: 8090 #set your port
