### Get all tasks
GET http://localhost:8090/api/v1/tasks
Accept: application/json

### Get task by id
GET http://localhost:8090/api/v1/tasks/19
Accept: application/json

### Create task
POST http://localhost:8090/api/v1/tasks
Content-Type: application/json

{
  "completed": false,
  "name": "Проверь обновление 1С (еженедельно)",
  "created": "2022-12-01T09:53:27.076264",
  "updated": "2022-12-01T09:53:27.076264",
  "categoryId": 1,
  "priorityId": 1,
  "supertaskId": null,
  "userId": 1
}
