### Get all tasks
GET http://localhost:8090/api/v1/tasks
Accept: application/json

### Get task by id
GET http://localhost:8090/api/v1/tasks/1
Accept: application/json

### Create task
POST http://localhost:8090/api/v1/tasks
Content-Type: application/json

{
  "completed": false,
  "name": "Проверь обновление 1С (еженедельно) 111",
  "until": null,
  "link": null,
  "created": "2022-11-30T22:26:31.969031",
  "updated": "2022-11-30T22:26:31.969031",
  "categoryId": 1,
  "priorityId": 1,
  "supertaskId": null,
  "userId": 1,
  "notes": []
}